#!/bin/sh

set -e
set -o xtrace

#5  add Percona GPG key
if [ ! -e /home/ubuntu/.gnupg ]; then
    mkdir -p /home/ubuntu/.gnupg
fi
#gpg --keyserver  hkp://keys.gnupg.net --recv-keys 1C4CBDCDCD2EFD2A
#gpg -a --export CD2EFD2A | apt-key add -
apt-key adv --keyserver hkp://keys.gnupg.net --recv-keys 1C4CBDCDCD2EFD2A

# add Percona repo
# XXX: autodetect distribution when Percona supports Quantal
RELEASE=${RELEASE:-precise}
cat <<EOL > /etc/apt/sources.list.d/percona.list
deb http://repo.percona.com/apt $RELEASE main
deb-src http://repo.percona.com/apt $RELEASE main
EOL


