#!/bin/sh

# Install controller base requiered packages

set -e
set -o xtrace

#DEBIAN_FRONTEND=noninteractive apt-get -y install sysstat mytop percona-toolkit percona-server-server-5.5 percona-server-client-5.5
export DEBIAN_FRONTEND=noninteractive
apt-get -y install language-pack-en
apt-get -y install sysstat mytop percona-toolkit ntp lvm2 xfsprogs xfsdump percona-server-common-5.5  percona-server-server-5.5 percona-server-test-5.5  percona-server-client-5.5 percona-xtrabackup policycoreutils python-pip python-dev libmysqlclient-dev