#!/bin/sh

dd of=/etc/init/reddwarf-guest.conf << _EOF_
description "Reddwarf Guest"
author "Auto-Gen"

start on (filesystem and net-device-up IFACE!=lo)
stop on runlevel [016]
chdir /var/run
pre-start script
    mkdir -p /var/run/reddwarf
    chown ubuntu:root /var/run/reddwarf/

    mkdir -p /var/lock/reddwarf
    chown ubuntu:root /var/lock/reddwarf/
end script

exec su -c /home/ubuntu/reddwarf/bin/reddwarf-guestagent --config-file="/home/ubuntu/reddwarf/etc/reddwarf/reddwarf-guestagent.conf.sample" ubuntu
_EOF_


