#!/bin/bash
# Save user SSH public key if available.
# XXX: Obviously not suitable for downloadable images.

set -e
set -o xtrace

if [ -e "/tmp/in_target.d/ssh-authorized-keys" ]; then
    ls -al /home/ubuntu
    if ! [ -e "/home/ubuntu/.ssh" ]; then
        sudo -Hiu ubuntu mkdir ~ubuntu/.ssh/
    fi
    sudo -Hiu ubuntu dd of=~ubuntu/.ssh/authorized_keys conv=notrunc if=/tmp/in_target.d/ssh-authorized-keys
    if ! [ -e "/home/ubuntu/.ssh/id_rsa" ]; then
        sudo -Hiu ubuntu dd of=~ubuntu/.ssh/id_rsa if=/tmp/in_target.d/id_rsa
        sudo -Hiu ubuntu dd of=~ubuntu/.ssh/id_rsa.pub if=/tmp/in_target.d/id_rsa.pub
    fi
fi
