#!/bin/bash

# Install controller base requiered packages

set -e
set -o xtrace

#DEBIAN_FRONTEND=noninteractive apt-get -y install sysstat mytop percona-toolkit percona-server-server-5.5 percona-server-client-5.5
export DEBIAN_FRONTEND=noninteractive
apt-get -y install sysstat mytop ntp lvm2 xfsprogs xfsdump policycoreutils libmysqlclient-dev