#!/bin/bash

# Install controller base requiered packages

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive
apt-get -y install language-pack-en
apt-get -y install percona-toolkit percona-server-common-5.5  percona-server-server-5.5 percona-server-test-5.5  percona-server-client-5.5 percona-xtrabackup